import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import {Header} from "@/app/_components/Header"; // Import Header as default export
import { Metadata } from "next";
import {Josefin_Sans} from "next/font/google"
const josefin = Josefin_Sans({
  subsets:["latin"],
  display:'swap'
});
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define props type for RootLayout component
type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
    <body className = {`${josefin.className} bg-primary-950 text-primary-100 min-h-screen flex flex-col relative  bg-gradient-to-l from-gray-200 to-blue-500 max-h-screen`}>
    <Header /> {/* Render Header component */}
    <main>
      <AppRouterCacheProvider>
    {children}
      </AppRouterCacheProvider>

    </main>
      </body>
    </html>
  );
}
